/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NewActivityAllOfOrg } from './newActivityAllOfOrg';
import { NewActivityAllOfProduct } from './newActivityAllOfProduct';
import { NewActivityAllOfScope } from './newActivityAllOfScope';
import { NewActivityAllOfTaxonomy } from './newActivityAllOfTaxonomy';

export class Activity {
    'uuid'?: string;
    'name'?: string;
    /**
    * ISO 8601 date
    */
    'created'?: string;
    /**
    * ISO 8601 date
    */
    'updated'?: string;
    /**
    * An identifier to use when syncing data with other systems. [Read more](/docs/syncId)
    */
    'syncId'?: string;
    'description'?: string;
    'quantity'?: number;
    /**
    * The unit code (e.g. kg, lbs, etc.). All unit codes can be found in the [List Units](/api-reference/v1/unit/get) endpoint.
    */
    'unit'?: string;
    /**
    * if passed, the value will be used instead of the computed value
    */
    'UpstreamCO2e'?: string;
    /**
    * if passed, the value will be used instead of the computed value
    */
    'DownstreamCO2e'?: string;
    'product'?: NewActivityAllOfProduct;
    'scope'?: NewActivityAllOfScope;
    'taxonomy'?: NewActivityAllOfTaxonomy;
    'org'?: NewActivityAllOfOrg;
    /**
    * ISO 8601 date
    */
    'startDate'?: string;
    /**
    * ISO 8601 date
    */
    'endDate'?: string;
    'CO2e'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string"
        },
        {
            "name": "syncId",
            "baseName": "syncId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "UpstreamCO2e",
            "baseName": "UpstreamCO2e",
            "type": "string"
        },
        {
            "name": "DownstreamCO2e",
            "baseName": "DownstreamCO2e",
            "type": "string"
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "NewActivityAllOfProduct"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "NewActivityAllOfScope"
        },
        {
            "name": "taxonomy",
            "baseName": "taxonomy",
            "type": "NewActivityAllOfTaxonomy"
        },
        {
            "name": "org",
            "baseName": "org",
            "type": "NewActivityAllOfOrg"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "CO2e",
            "baseName": "CO2e",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Activity.attributeTypeMap;
    }
}

