/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DataQualityIndicatorsEdit {
    'documentationYear'?: number;
    'coveragePercent'?: number;
    'specificPercent'?: number;
    'technologicalDQR'?: number;
    'geographicalDQR'?: number;
    'completenessDQR'?: number;
    'reliabilityDQR'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentationYear",
            "baseName": "documentationYear",
            "type": "number"
        },
        {
            "name": "coveragePercent",
            "baseName": "coveragePercent",
            "type": "number"
        },
        {
            "name": "specificPercent",
            "baseName": "specificPercent",
            "type": "number"
        },
        {
            "name": "technologicalDQR",
            "baseName": "technologicalDQR",
            "type": "number"
        },
        {
            "name": "geographicalDQR",
            "baseName": "geographicalDQR",
            "type": "number"
        },
        {
            "name": "completenessDQR",
            "baseName": "completenessDQR",
            "type": "number"
        },
        {
            "name": "reliabilityDQR",
            "baseName": "reliabilityDQR",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DataQualityIndicatorsEdit.attributeTypeMap;
    }
}

