/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FootprintCO2e } from './footprintCO2e';

/**
* Using `dataSource: external` allows setting certain `footprint.CO2e` values. The values are computed all other `dataSource`s.
*/
export class EditFootprint {
    'CO2e'?: FootprintCO2e;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "CO2e",
            "baseName": "CO2e",
            "type": "FootprintCO2e"
        }    ];

    static getAttributeTypeMap() {
        return EditFootprint.attributeTypeMap;
    }
}

