/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LifecycleStage } from './lifecycleStage';
import { NewInputBlock } from './newInputBlock';
import { NewInputMaterial } from './newInputMaterial';

export class EditInput {
    /**
    * An identifier to use when syncing data with other systems. [Read more](/docs/syncId)
    */
    'syncId'?: string;
    'quantity'?: number;
    /**
    * The unit code (e.g. kg, lbs, etc.). All unit codes can be found in the [List Units](/api-reference/v1/unit/get) endpoint.
    */
    'unit'?: string;
    'order'?: number;
    'material'?: NewInputMaterial;
    'block'?: NewInputBlock;
    'lifecycleStage'?: LifecycleStage;
    'uuid'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "syncId",
            "baseName": "syncId",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "material",
            "baseName": "material",
            "type": "NewInputMaterial"
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "NewInputBlock"
        },
        {
            "name": "lifecycleStage",
            "baseName": "lifecycleStage",
            "type": "LifecycleStage"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EditInput.attributeTypeMap;
    }
}

