/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FootprintCO2e {
    'totalCarbonFootprint'?: string;
    'productCarbonFootprint'?: string;
    'upstream'?: string;
    'direct'?: string;
    'downstream'?: string;
    'A1_A3'?: string;
    'A1'?: string;
    'A2'?: string;
    'A3'?: string;
    'A4'?: string;
    'B1'?: string;
    'B2'?: string;
    'B3'?: string;
    'B4'?: string;
    'B5'?: string;
    'C1'?: string;
    'C2'?: string;
    'C3'?: string;
    'C4'?: string;
    'D'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCarbonFootprint",
            "baseName": "totalCarbonFootprint",
            "type": "string"
        },
        {
            "name": "productCarbonFootprint",
            "baseName": "productCarbonFootprint",
            "type": "string"
        },
        {
            "name": "upstream",
            "baseName": "upstream",
            "type": "string"
        },
        {
            "name": "direct",
            "baseName": "direct",
            "type": "string"
        },
        {
            "name": "downstream",
            "baseName": "downstream",
            "type": "string"
        },
        {
            "name": "A1_A3",
            "baseName": "A1_A3",
            "type": "string"
        },
        {
            "name": "A1",
            "baseName": "A1",
            "type": "string"
        },
        {
            "name": "A2",
            "baseName": "A2",
            "type": "string"
        },
        {
            "name": "A3",
            "baseName": "A3",
            "type": "string"
        },
        {
            "name": "A4",
            "baseName": "A4",
            "type": "string"
        },
        {
            "name": "B1",
            "baseName": "B1",
            "type": "string"
        },
        {
            "name": "B2",
            "baseName": "B2",
            "type": "string"
        },
        {
            "name": "B3",
            "baseName": "B3",
            "type": "string"
        },
        {
            "name": "B4",
            "baseName": "B4",
            "type": "string"
        },
        {
            "name": "B5",
            "baseName": "B5",
            "type": "string"
        },
        {
            "name": "C1",
            "baseName": "C1",
            "type": "string"
        },
        {
            "name": "C2",
            "baseName": "C2",
            "type": "string"
        },
        {
            "name": "C3",
            "baseName": "C3",
            "type": "string"
        },
        {
            "name": "C4",
            "baseName": "C4",
            "type": "string"
        },
        {
            "name": "D",
            "baseName": "D",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FootprintCO2e.attributeTypeMap;
    }
}

