/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FootprintCO2eComputed {
    'totalCarbonFootprint'?: string;
    'productCarbonFootprint'?: string;
    'upstream'?: string;
    'direct'?: string;
    'downstream'?: string;
    'A1_A3'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCarbonFootprint",
            "baseName": "totalCarbonFootprint",
            "type": "string"
        },
        {
            "name": "productCarbonFootprint",
            "baseName": "productCarbonFootprint",
            "type": "string"
        },
        {
            "name": "upstream",
            "baseName": "upstream",
            "type": "string"
        },
        {
            "name": "direct",
            "baseName": "direct",
            "type": "string"
        },
        {
            "name": "downstream",
            "baseName": "downstream",
            "type": "string"
        },
        {
            "name": "A1_A3",
            "baseName": "A1_A3",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FootprintCO2eComputed.attributeTypeMap;
    }
}

