/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeoLocationBounds } from './geoLocationBounds';

export class GeoLocation {
    'uuid'?: string;
    'shortName'?: string;
    'googleMapsId'?: string;
    'locationType'?: string;
    'formattedAddress'?: string;
    'countryCode'?: string;
    'latitude'?: number;
    'longitude'?: number;
    'bounds'?: GeoLocationBounds;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "shortName",
            "baseName": "shortName",
            "type": "string"
        },
        {
            "name": "googleMapsId",
            "baseName": "googleMapsId",
            "type": "string"
        },
        {
            "name": "locationType",
            "baseName": "locationType",
            "type": "string"
        },
        {
            "name": "formattedAddress",
            "baseName": "formattedAddress",
            "type": "string"
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number"
        },
        {
            "name": "bounds",
            "baseName": "bounds",
            "type": "GeoLocationBounds"
        }    ];

    static getAttributeTypeMap() {
        return GeoLocation.attributeTypeMap;
    }
}

