/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReturnedInput } from './returnedInput';

export class GetModelInput200Response {
    'count'?: number;
    'page'?: number;
    'pageSize'?: number;
    'data'?: Array<ReturnedInput>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ReturnedInput>"
        }    ];

    static getAttributeTypeMap() {
        return GetModelInput200Response.attributeTypeMap;
    }
}

