/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PactProductFootprint } from './pactProductFootprint';

export class GetPactFootprintById200Response {
    'data'?: PactProductFootprint;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "PactProductFootprint"
        }    ];

    static getAttributeTypeMap() {
        return GetPactFootprintById200Response.attributeTypeMap;
    }
}

