/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PactProductCarbonFootprint } from './pactProductCarbonFootprint';

export class PactProductFootprint {
    'id'?: string;
    'specVersion'?: string;
    'precedingPfIds'?: Array<string>;
    'version'?: string;
    'status'?: string;
    'statusComment'?: string;
    'validityPeriodStart'?: Date;
    'validityPeriodEnd'?: Date;
    'companyName'?: string;
    'companyIds'?: Array<string>;
    'productIds'?: Array<string>;
    'productCategoryCpc'?: string;
    'productNameCompany'?: string;
    'productDescription'?: string;
    'comment'?: string;
    'pcf'?: PactProductCarbonFootprint;
    'extensions'?: Array<object>;
    'created'?: Date;
    'updated'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "specVersion",
            "baseName": "specVersion",
            "type": "string"
        },
        {
            "name": "precedingPfIds",
            "baseName": "precedingPfIds",
            "type": "Array<string>"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "statusComment",
            "baseName": "statusComment",
            "type": "string"
        },
        {
            "name": "validityPeriodStart",
            "baseName": "validityPeriodStart",
            "type": "Date"
        },
        {
            "name": "validityPeriodEnd",
            "baseName": "validityPeriodEnd",
            "type": "Date"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "companyIds",
            "baseName": "companyIds",
            "type": "Array<string>"
        },
        {
            "name": "productIds",
            "baseName": "productIds",
            "type": "Array<string>"
        },
        {
            "name": "productCategoryCpc",
            "baseName": "productCategoryCpc",
            "type": "string"
        },
        {
            "name": "productNameCompany",
            "baseName": "productNameCompany",
            "type": "string"
        },
        {
            "name": "productDescription",
            "baseName": "productDescription",
            "type": "string"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "pcf",
            "baseName": "pcf",
            "type": "PactProductCarbonFootprint"
        },
        {
            "name": "extensions",
            "baseName": "extensions",
            "type": "Array<object>"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PactProductFootprint.attributeTypeMap;
    }
}

