/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProductOrSectorSpecificRuleInner {
    'operator'?: string;
    'ruleNames'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string"
        },
        {
            "name": "ruleNames",
            "baseName": "ruleNames",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ProductOrSectorSpecificRuleInner.attributeTypeMap;
    }
}

