/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataQualityIndicators } from './dataQualityIndicators';
import { Footprint } from './footprint';
import { NewProductAllOfGeoLocation } from './newProductAllOfGeoLocation';
import { NewProductAllOfLocation } from './newProductAllOfLocation';
import { NewProductAllOfTaxonomy } from './newProductAllOfTaxonomy';
import { ProductDataSource } from './productDataSource';

export class Product {
    'uuid'?: string;
    'dataSource'?: ProductDataSource;
    'name'?: string;
    'description'?: string;
    'sku'?: string;
    /**
    * An identifier to use when syncing data with other systems. [Read more](/docs/syncId)
    */
    'syncId'?: string;
    'cpcCode'?: string;
    /**
    * The unit code (e.g. kg, lbs, etc.). All unit codes can be found in the [List Units](/api-reference/v1/unit/get) endpoint.
    */
    'unit'?: string;
    'footprint'?: Footprint;
    'dataQualityIndicators'?: DataQualityIndicators;
    'taxonomy'?: NewProductAllOfTaxonomy;
    'geoLocation'?: NewProductAllOfGeoLocation;
    'location'?: NewProductAllOfLocation;
    /**
    * ISO 8601 date
    */
    'startDate'?: string;
    /**
    * ISO 8601 date
    */
    'endDate'?: string;
    /**
    * ISO 8601 date
    */
    'created'?: string;
    /**
    * ISO 8601 date
    */
    'updated'?: string;
    'image'?: string;
    'dataQualityRating'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "dataSource",
            "baseName": "dataSource",
            "type": "ProductDataSource"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string"
        },
        {
            "name": "syncId",
            "baseName": "syncId",
            "type": "string"
        },
        {
            "name": "cpcCode",
            "baseName": "cpcCode",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "footprint",
            "baseName": "footprint",
            "type": "Footprint"
        },
        {
            "name": "dataQualityIndicators",
            "baseName": "dataQualityIndicators",
            "type": "DataQualityIndicators"
        },
        {
            "name": "taxonomy",
            "baseName": "taxonomy",
            "type": "NewProductAllOfTaxonomy"
        },
        {
            "name": "geoLocation",
            "baseName": "geoLocation",
            "type": "NewProductAllOfGeoLocation"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "NewProductAllOfLocation"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "dataQualityRating",
            "baseName": "dataQualityRating",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product.attributeTypeMap;
    }
}

export namespace Product {
}
