/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SwitchAllOfFootprintCO2e } from './switchAllOfFootprintCO2e';

export class SwitchAllOfFootprint {
    'CO2e'?: SwitchAllOfFootprintCO2e;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "CO2e",
            "baseName": "CO2e",
            "type": "SwitchAllOfFootprintCO2e"
        }    ];

    static getAttributeTypeMap() {
        return SwitchAllOfFootprint.attributeTypeMap;
    }
}

