/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IDAndName } from './iDAndName';
import { SwitchAllOfFootprint } from './switchAllOfFootprint';

export class Switch {
    /**
    * An identifier to use when syncing data with other systems. [Read more](/docs/syncId)
    */
    'syncId'?: string;
    'name'?: string;
    /**
    * The unit code (e.g. kg, lbs, etc.). All unit codes can be found in the [List Units](/api-reference/v1/unit/get) endpoint.
    */
    'unit'?: string;
    /**
    * ISO 8601 date
    */
    'created'?: string;
    /**
    * ISO 8601 date
    */
    'updated'?: string;
    'uuid'?: string;
    'image'?: string;
    'sources'?: Array<IDAndName>;
    'footprint'?: SwitchAllOfFootprint;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "syncId",
            "baseName": "syncId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<IDAndName>"
        },
        {
            "name": "footprint",
            "baseName": "footprint",
            "type": "SwitchAllOfFootprint"
        }    ];

    static getAttributeTypeMap() {
        return Switch.attributeTypeMap;
    }
}

