/**
 * Variable API
 * This is the Variable API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Activity } from './activity';
import { Org } from './org';
import { Scope } from './scope';
import { Taxonomy } from './taxonomy';

export class V1ActivityDataGet200Response {
    'count'?: number;
    'page'?: number;
    'pageSize'?: number;
    'data'?: Array<Activity>;
    /**
    * The query string used to filter the activities
    */
    'queryString'?: string;
    /**
    * ISO 8601 date
    */
    'startDate'?: string;
    /**
    * ISO 8601 date
    */
    'endDate'?: string;
    /**
    * The total CO2e of all activities categorized to a GHG Scope, in `CO2eUnit`
    */
    'CO2e'?: string;
    /**
    * The total CO2e of all activities *not* categorized to a GHG Scope, in `CO2eUnit`
    */
    'uncategorizedCO2e'?: string;
    /**
    * The unit of CO2e. For example \"kg\"
    */
    'CO2eUnit'?: string;
    /**
    * A list of GHG Scopes used in the result set
    */
    'scopes'?: Array<Scope>;
    /**
    * A list of Orgs used in the result set
    */
    'orgs'?: Array<Org>;
    /**
    * A list of Taxonomies used in the result set
    */
    'taxonomies'?: Array<Taxonomy>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Activity>"
        },
        {
            "name": "queryString",
            "baseName": "queryString",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "CO2e",
            "baseName": "CO2e",
            "type": "string"
        },
        {
            "name": "uncategorizedCO2e",
            "baseName": "uncategorizedCO2e",
            "type": "string"
        },
        {
            "name": "CO2eUnit",
            "baseName": "CO2eUnit",
            "type": "string"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<Scope>"
        },
        {
            "name": "orgs",
            "baseName": "orgs",
            "type": "Array<Org>"
        },
        {
            "name": "taxonomies",
            "baseName": "taxonomies",
            "type": "Array<Taxonomy>"
        }    ];

    static getAttributeTypeMap() {
        return V1ActivityDataGet200Response.attributeTypeMap;
    }
}

